### ISSUE TITLE
URI::InvalidURIError: bad URI(is not URI?)

### ISSUE THREAD

**Issue by inhumantsar** [JFrogDev/knife-art#1]
So we're trying out the Chef repos on a cloud Artifactory. We've got a virtual set up in front of a remote and a local repo. Currently, there is nothing in any of those repos. My user account is Okta/SAML backed and has full access to the repos. This is a fresh CentOS 7 Docker container with the latest ChefDK installed (v1.2.22). The knife plugin was installed as per the docs: `chef gem install knife-art` and I configured Chef according to the Set Me Up directions provided by Artifactory.

Some context follows.
```
# cat /root/.chef/knife.rb 
knife[:supermarket_site] = 'https://smartin%40somedomain%2Ecom:longurlencodedpasswithspecialchars@prefix.artifactoryonline.com/prefix/api/chef/chef-virtual'

# echo $PATH
/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/chefdk/embedded/bin:/root/.chefdk/gem/ruby/2.3.0/bin

# which chef
/opt/chefdk/embedded/bin/chef

[root@d1f94c4ff54b /]# which knife
/opt/chefdk/embedded/bin/knife

[root@8c2e88b5c351 /]# knife -v
Chef: 12.18.31

[root@8c2e88b5c351 /]# chef gem list knife-art -d

*** LOCAL GEMS ***

knife-art (1.0.0)
    Author: Dan Feldman
    Homepage: https://github.com/JFrogDev/knife-art
    License: Apache-2.0
    Installed at: /root/.chefdk/gem/ruby/2.3.0

    Artifactory integration for Knife
[root@8c2e88b5c351 /]# knife artifactory
FATAL: Cannot find subcommand for: 'artifactory'
Available artifactory subcommands: (for details, knife SUB-COMMAND --help)

** ARTIFACTORY COMMANDS **
knife artifactory download COOKBOOK [VERSION] (options)
knife artifactory install COOKBOOK [VERSION] (options)
knife artifactory list (options)
knife artifactory search QUERY (options)
knife artifactory share COOKBOOK [CATEGORY] (options)
knife artifactory show COOKBOOK [VERSION] (options)
knife artifactory unshare COOKBOOK VERSION
```

And now the errors:
```
# with username (email address) and password url-encoded
# also get this error when dropping the urlencoded "@somedomain.com" portion
# knife artifactory list -VV
INFO: Using configuration from /root/.chef/knife.rb
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_request
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_request
DEBUG: Initiating GET to https://smartin%40somedomain%2Ecom:somelongurlencodedpasswordwithspecialchars@prefix.artifactoryonline.com/prefix/api/chef/chef-virtual/api/v1/cookbooks?items=10&start=0
DEBUG: ---- HTTP Request Header Data: ----
DEBUG: Accept: application/json
DEBUG: Accept-Encoding: gzip;q=1.0,deflate;q=0.6,identity;q=0.3
DEBUG: X-REMOTE-REQUEST-ID: 795f2bdf-4d2e-441f-9d1b-c8de85822f42
DEBUG: ---- End HTTP Request Header Data ----
DEBUG: ---- HTTP Status and Header Data: ----
DEBUG: HTTP 1.1 401 Unauthorized
DEBUG: content-type: application/json;charset=ISO-8859-1
DEBUG: date: Mon, 06 Mar 2017 20:11:32 GMT
DEBUG: server: Artifactory/5.1.0
DEBUG: www-authenticate: Basic realm="Artifactory Realm"
DEBUG: x-artifactory-id: aolshared8c-prefix
DEBUG: x-node: nginx-shared2e.prod-use1
DEBUG: content-length: 80
DEBUG: connection: Close
DEBUG: ---- End HTTP Status/Header Data ----
DEBUG: ---- HTTP Response Body ----
DEBUG: {
  "errors" : [ {
    "status" : 401,
    "message" : "Bad credentials"
  } ]
}
DEBUG: ---- End HTTP Response Body -----
DEBUG: Chef::HTTP calling Chef::HTTP::ValidateContentLength#handle_response
DEBUG: Content-Length validated correctly.
DEBUG: Chef::HTTP calling Chef::HTTP::RemoteRequestID#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::Decompressor#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::CookieManager#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONOutput#handle_response
DEBUG: Chef::HTTP calling Chef::HTTP::JSONInput#handle_response
INFO: HTTP Request Returned 401 Unauthorized: 
/opt/chefdk/embedded/lib/ruby/2.3.0/net/http/response.rb:120:in `error!': 401 "Unauthorized" (Net::HTTPServerException)
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/http.rb:150:in `request'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/http.rb:115:in `get'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife/cookbook_site_list.rb:52:in `get_cookbook_list'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife/cookbook_site_list.rb:46:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/embedded/bin/knife:22:in `load'
	from /opt/chefdk/embedded/bin/knife:22:in `<main>'


# with raw username (email address) and url-encoded password
# also with raw username (email address) and password:
# knife artifactory list -VV
INFO: Using configuration from /root/.chef/knife.rb
/opt/chefdk/embedded/lib/ruby/2.3.0/uri/rfc3986_parser.rb:67:in `split': bad URI(is not URI?): https://smartin@somedomain.com:somelong(urlencoded)passwordwithspecialchars@prefix.artifactoryonline.com/prefix/api/chef/chef-virtual/api/v1/cookbooks?items=10&start=0 (URI::InvalidURIError)
	from /opt/chefdk/embedded/lib/ruby/2.3.0/uri/rfc3986_parser.rb:73:in `parse'
	from /opt/chefdk/embedded/lib/ruby/2.3.0/uri/common.rb:227:in `parse'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/http.rb:281:in `create_url'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/http.rb:145:in `request'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/http.rb:115:in `get'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife/cookbook_site_list.rb:52:in `get_cookbook_list'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife/cookbook_site_list.rb:46:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife.rb:443:in `block in run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/local_mode.rb:44:in `with_server_connectivity'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife.rb:442:in `run_with_pretty_exceptions'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/knife.rb:219:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/lib/chef/application/knife.rb:156:in `run'
	from /opt/chefdk/embedded/lib/ruby/gems/2.3.0/gems/chef-12.18.31/bin/knife:25:in `<top (required)>'
	from /opt/chefdk/embedded/bin/knife:22:in `load'
	from /opt/chefdk/embedded/bin/knife:22:in `<main>'
```

And some Artifactory logs:
```
# matching timestamps in access.log
2017-03-06 20:04:17,884 [DENIED LOGIN]  for NA/1.2.3.4.
2017-03-06 20:05:36,041 [DENIED LOGIN]  for NA/1.2.3.4.
2017-03-06 20:06:45,761 [DENIED LOGIN]  for NA/1.2.3.4.
2017-03-06 20:11:32,717 [DENIED LOGIN]  for NA/1.2.3.4.
2017-03-06 20:13:07,646 [DENIED LOGIN]  for NA/1.2.3.4.

# matching timestamps in requests.log
20170306200417|10|REQUEST|1.2.3.4|non_authenticated_user|GET|/api/chef/chef-virtual/api/v1/cookbooks|HTTP/1.1|401|0
20170306200536|8|REQUEST|1.2.3.4|non_authenticated_user|GET|/api/chef/chef-virtual/api/v1/cookbooks|HTTP/1.1|401|0
20170306200645|7|REQUEST|1.2.3.4|non_authenticated_user|GET|/api/chef/chef-virtual/api/v1/cookbooks|HTTP/1.1|401|0
20170306201132|8|REQUEST|1.2.3.4|non_authenticated_user|GET|/api/chef/chef-virtual/api/v1/cookbooks|HTTP/1.1|401|0
20170306201307|4|REQUEST|1.2.3.4|non_authenticated_user|GET|/api/chef/chef-virtual/api/v1/cookbooks|HTTP/1.1|401|0
```

Not sure where to go from here. I'm fairly knowledgeable in Chef, but I've never written a Knife plugin before. I should be seeing [this line](https://github.com/JFrogDev/knife-art/blob/master/lib/knife-art/knife_art_utils.rb#L8) in the output at least right?

**Comment by 85danf** [comment]
Hi and thanks for reporting this,

The `list` code does not reach that part in the code, although the plugin uses the same method to parse the url eventually (evident in the trace you gave - error originates in knife's code).  
That being said, it would happen with other commands as well because we do use the same logic.

We're looking into possible ways to work around this (and have a permanent solution eventually) - I'll get back to you soon.

**Comment by 85danf** [comment]
So we tested this here - SAML authentication for non-ui operations requires that you have an internal user set up so it has an internal password or api key.

Once we setup an internal password for our SAML user the usecase you describe (username with encoded `@`) worked for us.

Can you please re-check and confirm?

**Comment by inhumantsar** [comment]
Yep, can confirm, that does the trick. Would it be possible to update the docs to be more explicit about that?

**Comment by 85danf** [comment]
It's a bit too specific to be included in the plugin's doc as it's more of an Artifactory topic.
It is documented in our wiki though - 

https://www.jfrog.com/confluence/display/RTF/SAML+SSO+Integration#SAMLSSOIntegration-UsingAPIKeywithSAMLUsers

I'm closing this issue, thanks for giving the client a spin :)
